import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/lib/react-query/QueryProvider";
import localFont from 'next/font/local';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const vazirmatn = localFont({
  src: [
    {
      path: '../fonts/Vazirmatn-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/Vazirmatn-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../fonts/Vazirmatn-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
});
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="fa"
       dir="rtl" className={vazirmatn.className}
    >
        <body>
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
